// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzezhmsqzqanolpwjgec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZXpobXNxenFhbm9scHdqZ2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTI3NTUsImV4cCI6MjA3MTgyODc1NX0.D2bczK_7TbbgoQaPKjo7K2YuS4ySb5nvOpm2EF9ZTP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});